# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Document-Transport
version:      0.2
version_from: 
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0
    File::Spec:                    0
    Net::Domain:                   0
    XML::Simple:                   0
    XML::Writer:                   0
    XML::Writer::String:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
